import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { adminDb } from "@/lib/firebase-admin";
import { transcribeAudio } from "@/lib/sarvam";
import { analyzeTranscript } from "@/lib/gemini";
import { createGitHubIssue } from "@/lib/github";
import { createJiraTicket } from "@/lib/jira";
import { createNotionPage } from "@/lib/notion";
import { v4 as uuidv4 } from "uuid";

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session?.user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const formData = await req.formData();
    const audioFile = formData.get("audio") as File | null;
    const transcript = formData.get("transcript") as string | null;
    const meetingId = formData.get("meeting_id") as string;
    const projectId = formData.get("project_id") as string;
    const teamId = formData.get("team_id") as string;

    // Get team members for better AI assignment
    const teamDoc = await adminDb.collection("teams").doc(teamId).get();
    const teamMembers: string[] = teamDoc.exists
      ? (teamDoc.data()?.members as string[]) || []
      : [];

    // Get project info for GitHub/Notion
    const projectDoc = await adminDb.collection("projects").doc(projectId).get();
    const projectData = projectDoc.data();

    let finalTranscript = transcript || "";

    if (audioFile && !finalTranscript) {
      // Check if it's a text file
      if (audioFile.name.endsWith('.txt') || audioFile.type === 'text/plain') {
        const textData = await audioFile.text();
        finalTranscript = textData;
      } else {
        // If audio/video file provided, transcribe with Sarvam AI
        const buffer = Buffer.from(await audioFile.arrayBuffer());
        finalTranscript = await transcribeAudio(buffer, audioFile.name);
      }
    }

    if (!finalTranscript) {
      return NextResponse.json({ error: "No transcript or audio provided" }, { status: 400 });
    }

    // Update meeting with transcript
    await adminDb.collection("meetings").doc(meetingId).update({
      transcript: finalTranscript,
      status: "processing",
    });

    // Analyze transcript with Gemini
    const analysis = await analyzeTranscript(finalTranscript, teamMembers);

    // Create tasks in Firestore + integrations
    const createdTasks = [];

    for (const task of analysis.tasks) {
      const taskId = uuidv4();
      let githubUrl: string | null = null;
      let githubNumber: number | null = null;
      let jiraUrl: string | null = null;
      let jiraKey: string | null = null;

      // GitHub Issue
      if (
        projectData?.github_owner &&
        projectData?.github_repo &&
        process.env.GITHUB_TOKEN !== "placeholder"
      ) {
        try {
          // First attempt: with assignees
          let assignees = task.assigned_to ? [task.assigned_to] : [];
          
          try {
            const issue = await createGitHubIssue(
              projectData.github_owner,
              projectData.github_repo,
              {
                title: task.title,
                body: `**Description:** ${task.description}\n\n**Type:** ${task.type}\n**Priority:** ${task.priority}\n\n_Generated by Meet2Task AI from meeting: ${meetingId}_`,
                assignees: assignees,
                labels: ["meet2task", task.type],
              }
            );
            githubUrl = issue.url;
            githubNumber = issue.number;
          } catch (firstAttemptError: any) {
            // If the failure was due to the assignee not being a collaborator or invalid, try without assignee
            console.log("Failed to create GH issue with assignee, falling back without assignee...");
            const fallbackIssue = await createGitHubIssue(
              projectData.github_owner,
              projectData.github_repo,
              {
                title: task.title,
                body: `**Description:** ${task.description}\n\n**Type:** ${task.type}\n**Priority:** ${task.priority}\n\n**Intended Assignee:** @${task.assigned_to} (User is not a collaborator on this repo so auto-assignment failed)\n\n_Generated by Meet2Task AI from meeting: ${meetingId}_`,
                assignees: [], // Clear assignees!
                labels: ["meet2task", task.type],
              }
            );
            githubUrl = fallbackIssue.url;
            githubNumber = fallbackIssue.number;
          }
        } catch (e) {
          console.error("GitHub issue creation ultimately failed:", e);
        }
      }

      // Jira Ticket
      if (
        process.env.JIRA_BASE_URL !== "https://placeholder.atlassian.net" &&
        process.env.JIRA_API_TOKEN !== "placeholder"
      ) {
        try {
          const jira = await createJiraTicket({
            title: task.title,
            description: task.description,
            priority:
              task.priority === "high"
                ? "High"
                : task.priority === "medium"
                ? "Medium"
                : "Low",
            issuetype: task.type === "bug" ? "Bug" : "Task",
          });
          jiraUrl = jira.url;
          jiraKey = jira.key;
        } catch (e) {
          console.error("Jira ticket creation failed:", e);
        }
      }

      const taskDoc = {
        task_id: taskId,
        meeting_id: meetingId,
        project_id: projectId,
        title: task.title,
        description: task.description,
        assigned_to: task.assigned_to,
        status: "open",
        priority: task.priority,
        type: task.type,
        deadline: task.deadline,
        github_issue_url: githubUrl,
        github_issue_number: githubNumber,
        jira_issue_url: jiraUrl,
        jira_issue_key: jiraKey,
        created_at: new Date().toISOString(),
      };

      await adminDb.collection("tasks").doc(taskId).set(taskDoc);
      createdTasks.push(taskDoc);
    }

    // Notion page for meeting notes
    let notionUrl: string | null = null;
    if (
      process.env.NOTION_TOKEN !== "placeholder" &&
      process.env.NOTION_DATABASE_ID !== "placeholder"
    ) {
      try {
        const notion = await createNotionPage({
          title: `Meeting Notes - ${new Date().toLocaleDateString()}`,
          summary: analysis.summary,
          decisions: analysis.decisions,
          meeting_date: new Date().toISOString().split("T")[0],
          project_name: projectData?.project_name || "Unknown Project",
        });
        notionUrl = notion.url;
      } catch (e) {
        console.error("Notion page creation failed:", e);
      }
    }

    // Update meeting as completed
    await adminDb.collection("meetings").doc(meetingId).update({
      status: "completed",
      summary: analysis.summary,
      decisions: analysis.decisions,
      key_points: analysis.key_points,
      transcript: finalTranscript,
      notion_url: notionUrl,
    });

    return NextResponse.json({
      success: true,
      meeting_id: meetingId,
      transcript: finalTranscript,
      analysis,
      tasks: createdTasks,
      notion_url: notionUrl,
    });
  } catch (error) {
    console.error("Meeting analysis error:", error);
    return NextResponse.json(
      { error: "Failed to process meeting" },
      { status: 500 }
    );
  }
}
